import type { PageContentSchema } from '../page-content-types';

export const regulationsDefaults: PageContentSchema = {
  pageId: 'regulations',
  title: 'Regulations',
  sections: [
    {
      id: 'header', title: 'Regulations', blocks: [
        { type: 'hero', icon: 'Scale', title: 'RMLL Regulations', subtitle: 'Rocky Mountain Lacrosse League — Alberta Amateur Major Lacrosse Regulations. These regulations govern playing divisions, franchises, fees, facilities, player eligibility, rosters, trades, playoffs, discipline, and all operational aspects of the RMLL.<br/><em>Revised — December 1, 2024</em>' },
      ],
    },
    // ═══ GENERAL & STRUCTURE ═══
    {
      id: 'reg-1', title: '1 — General', icon: 'Scale', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>1.1</strong> The Regulations of the RMLL are subject to the Bylaws, Regulations, and Policies imposed by Lacrosse Canada ("LC") and the Alberta Lacrosse Association ("ALA"). Where a conflict arises between these Regulations and the Bylaws, Regulations, and Policies of the ALA or LC, the ALA or LC rules will govern.' },
        { type: 'paragraph', text: '<strong>1.2</strong> Each RMLL primary contact, secondary contact, coach, manager, and trainer, as an official of the Franchise, is responsible for reading, understanding, and the proper observance of the RMLL Bylaws and Regulations as well as LC and ALA Bylaws, Regulations, and Policies.' },
        { type: 'paragraph', text: '<strong>1.3</strong> RMLL Regulations are the general rules which govern all the Divisions within the RMLL.' },
        { type: 'paragraph', text: '<strong>1.3.1</strong> These Regulations of the RMLL shall not be amended except as described within the Bylaws of the RMLL.' },
        { type: 'paragraph', text: '<strong>1.3.2</strong> Each Member shall be entitled to a copy of the Regulations of the RMLL as published by the RMLL from time to time.' },
        { type: 'paragraph', text: '<strong>1.4</strong> A Division Operating Policy, ratified annually by the RMLL Executive, may have further additions to and/or establish certain rules within the jurisdiction and sanction of the RMLL Mission Statement, Bylaws, and Regulations.' },
        { type: 'paragraph', text: '<strong>1.4.1</strong> A Division Operating Policy shall only include the additional regulations specific to the Division and shall not include regulations stated elsewhere.' },
        { type: 'paragraph', text: '<strong>1.4.2</strong> A Division Operating Policy shall not be amended except as described within the Bylaws of the RMLL.' },
        { type: 'paragraph', text: '<strong>1.4.3</strong> If a conflict arises between a Division Operating Policy and these Regulations, these Regulations will govern.' },
        { type: 'paragraph', text: '<strong>1.5</strong> Any Division may elect an Assistant Commissioner by a majority vote of the Franchises in their Division to be put forward for ratification to the RMLL Executive.' },
        { type: 'paragraph', text: '<strong>1.5.1</strong> The term of the Assistant Commissioner shall be from the date of their ratification by the RMLL Executive until the next succeeding annual division planning meeting of the Division.' },
        { type: 'paragraph', text: '<strong>1.5.2</strong> The function of the Assistant Commissioner shall be to assist the Commissioner of the Division which such administrative and other functions as determined by the Commissioner, provided same does not conflict with those functions assigned to the Commissioner pursuant to the provisions of Section 7.05.3 of the Bylaws of the RMLL.' },
      ],
    },
    {
      id: 'reg-2', title: '2 — Playing Divisions', icon: 'Scale', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>2.1</strong> The RMLL governs the following playing Divisions: Senior A (when established), Senior B, Senior C, Junior A, Junior B Tier I, Junior B Tier II, Junior B Tier III, Senior Major Female and Junior Major Female.' },
        { type: 'paragraph', text: '<strong>2.2</strong> The RMLL, through the Executive, reserves to itself the right to move a Franchise from one Division to another if the Executive deems to be in the best interest of the lacrosse.' },
        { type: 'paragraph', text: '<strong>2.3</strong> An RMLL Division with more than five (5) Franchises may establish sub-divisions of no less than three (3) Franchises in each sub-division.' },
        { type: 'paragraph', text: '<strong>2.4</strong> A RMLL Division may play Regular Season interlock games with another RMLL Division with the approval of each of the affected Divisions and the RMLL Executive.' },
      ],
    },
    {
      id: 'reg-3', title: '3 — Franchises', icon: 'Scale', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>3.1</strong> A Franchise is a group of persons comprised of not less than twenty (20) players with at least one Coach, all of whom are registered with the RMLL. At the discretion of the Division Commissioner, the minimum of 20 players may be waived. Each Franchise accepted by the RMLL Executive shall be entitled to a Franchise Certificate certifying the Franchise Holder holds a Franchise in the RMLL.' },
        { type: 'paragraph', text: '<strong>3.2</strong> To apply for a Franchise Certificate or to request a Franchise Certificate reinstatement, the potential Franchise Holder must submit a completed "New Franchise Certificate Request" signed by the duly authorized Officers of the registered body corporate to the RMLL Executive Director as per the annual deadline. See Schedule 2.' },
        { type: 'paragraph', text: '<strong>3.3</strong> To request a transfer to another RMLL Division for the upcoming season the Franchise Holder must submit a completed "Division Tier Change Request" signed by a duly authorized Officer to the RMLL Executive Director as per the annual deadline. See Schedule 3.' },
        { type: 'paragraph', text: '<strong>3.4</strong> Each Franchise Holder must complete on an annual basis a Franchise Certificate in the RMLL Franchise Management System by the annual deadline.' },
        { type: 'paragraph', text: '<strong>3.4.1</strong> The Franchise Certificate contacts include but are not limited to the Board of Directors and/or Officers/Executive, primary Franchise contact, secondary Franchise contact, financial contact, scheduling contact, Franchise registrar, manager, head coach, assistant coaches, and trainers.' },
        { type: 'paragraph', text: '<strong>3.4.2</strong> Name, mailing address, home number or cell number, and e-mail address are required for each contact. In addition, the NCCP number is required for both Head and Assistant Coaches.' },
        { type: 'paragraph', text: '<strong>3.5</strong> A duly authorized Officer of the Franchise Holder must complete and sign the Franchise Certificate Form and return it to the RMLL Executive Director. See Schedule 5.' },
        { type: 'paragraph', text: '<strong>3.6</strong> The Primary or the Secondary Contact holds the one vote for the Franchise and one person may not represent more than one RMLL Franchise as a Primary Contact.' },
        { type: 'paragraph', text: '<strong>3.7</strong> The Franchise may be sold or transferred subject to the approval of the majority of the teams of that Division and the RMLL Executive.' },
        { type: 'paragraph', text: '<strong>3.7.1</strong> Application for approval of a Franchise transfer must be submitted in writing to the RMLL Executive Director prior to November 1 of the past playing Season. See Schedule 4.' },
        { type: 'paragraph', text: '<strong>3.8</strong> The approval process for a transfer of a RMLL Franchise requires minutes of each body approving the transfer, filing of the contract or agreement, and the proposed Franchise transferee becomes a member of a member association of the LC.' },
        { type: 'paragraph', text: '<strong>3.9</strong> A Franchise Holder will continue to hold the Franchise Certificate unless: the member association of the LC does not approve its application; the Franchise is expelled by the RMLL Executive; or the Franchise Holder submits written notification relinquishing their Franchise Certificate.' },
      ],
    },
    {
      id: 'reg-4', title: '4 — Annual Filings', icon: 'Scale', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>4.1</strong> Each Franchise Holder must file with the RMLL Executive Director on an annual basis proof of filings of their annual return and Schedule 5.' },
      ],
    },
    {
      id: 'reg-5', title: '5 — Fees and Bonds', icon: 'DollarSign', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>5.1</strong> An application for a new Franchise Certificate, a Tier Change request and a Franchise Transfer request must include a refundable application bond of $1,500.00.' },
        { type: 'paragraph', text: '<strong>5.1.1</strong> The bond will be held by the RMLL for a probationary period the later of twenty-four (24) months or two (2) playing seasons. At the end of the probationary period the entire bond will be refunded if the Franchise has not defaulted a game and has no money owing to the RMLL.' },
        { type: 'paragraph', text: '<strong>5.2</strong> The annual Franchise Fee of $950.00 and a $200.00 contingency fund is payable by March 1. Failure to pay fees when due may result in a Franchise being denied the ability to participate in all sanctioned RMLL activities.' },
        { type: 'paragraph', text: '<strong>5.3–5.4</strong> For New Franchise Requests, the Franchise Fee must accompany the submission request and will not be refunded if the Franchise is withdrawn after a Franchise Certificate has been granted. The annual Franchise Fee for a Franchise holding an existing Franchise will not be refunded if a team withdraws after February 1.' },
        { type: 'paragraph', text: '<strong>5.5</strong> Each Franchise Holder is required to submit a performance bond of $2,000.00 with the Franchise request.' },
        { type: 'paragraph', text: '<strong>5.5.1</strong> If a Franchise Holder voluntarily withdraws between September 1 and December 31, the performance bond will be refunded if the Franchise has no money owing to the RMLL.' },
        { type: 'paragraph', text: '<strong>5.5.2</strong> If a Franchise Holder withdraws between February 1 and prior to the end of the current playing Season, the performance bond will not be refunded.' },
        { type: 'paragraph', text: '<strong>5.6–5.7</strong> Interest earned on bond monies shall become revenue of the RMLL and be allocated to general funds. The RMLL will invoice each Franchise Holder in a Division qualifying for Provincials the ALA Provincial Entry Fee as set annually by the ALA.' },
        { type: 'paragraph', text: '<strong>5.8</strong> Each Franchise in the Senior B Division must submit a Presidents\' Cup Travel Fund Levy of $500.00, payable by March 1.' },
        { type: 'paragraph', text: '<strong>5.9</strong> Each Franchise in the Junior A Division will be invoiced $3,000.00 for the Junior A Division Minto Travel Equalization Account payable by March 1.' },
        { type: 'paragraph', text: '<strong>5.10</strong> Each Alberta Franchise in the Junior B Tier I Division must submit a Founders\' Cup Travel Fund Levy of $500.00, payable by March 1.' },
        { type: 'paragraph', text: '<strong>5.11–5.13</strong> When the Larry Bishop Memorial Cup is a Tier I playoff format, expenses split by Franchises. Each Alberta Tier I Franchise submits $3,000 for Travel Account. Each Tier II Franchise invoiced $150 Playoff Floor/Official Fee and $250 Playoff/Provincial Travelling Fee, payable by March 1.' },
        { type: 'paragraph', text: '<strong>5.14–5.15</strong> During the Season, a Franchise will be invoiced for Official accommodation and/or Official airfare. At end of Season, each Franchise is invoiced for ALRA Assigning Fee and fees for mileage and per diems. Fee rates are as per ALA Regulations.' },
        { type: 'paragraph', text: '<strong>5.16</strong> All fees shall be paid to: Rocky Mountain Lacrosse League, PO Box 47083 Creekside, Calgary, Alberta, T3P 0B9.' },
        { type: 'paragraph', text: '<strong>5.17</strong> All RMLL invoices are due thirty (30) days from invoice date except invoices for fines, Provincial Entry Fees, Official accommodation, Official airfare and RMLL/ALRA End of Season Fees which are due ten (10) days.' },
        { type: 'paragraph', text: '<strong>5.18–5.22</strong> NSF cheque fine: $50.00. Additional fees from other groups are in addition to RMLL fees. All fees and fines go into the RMLL General Account. 90% of casino profits allotted to the RMLL. An annual player registration fee may be established for each Division.' },
      ],
    },
    {
      id: 'reg-6', title: '6 — Facilities', icon: 'Landmark', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>6.1</strong> Each Franchise is responsible for acquiring their home arena and booking the arena for their home games. The arena must conform to RMLL facility requirements (Schedule 6), have an Official Change Room with a shower, and be approved by the RMLL Executive.' },
        { type: 'paragraph', text: '<strong>6.1.1</strong> Games may not be held in Soccer Centres or Field Houses unless the ALA has approved the facility, the majority of teams in the Division vote in favour, and the RMLL Executive has ratified the use.' },
        { type: 'paragraph', text: '<strong>6.2–6.3</strong> All Franchises must send facility specifications to the RMLL Executive Director and enter their home and back-up arena in the RMLL Franchise Management System prior to January 1.' },
        { type: 'paragraph', text: '<strong>6.4</strong> The home Franchise is responsible for: correct floor line markings, LC approved nets of correct size, good condition black mesh, two LC approved shot clocks, operational score clock with electronic buzzer, and score clock to count down penalty minutes.' },
        { type: 'paragraph', text: '<strong>6.5–6.7</strong> The home Franchise shall be held responsible for assuring the playing area is suitable for all games. No Franchise may change its home game from one arena to another without prior permission of the Division Commissioner. As per ALA Regulation 6B.03 all facility contracts for Major Lacrosse Provincials must be in the name of Alberta Lacrosse Association unless approved by the ALA Executive Director.' },
      ],
    },
    {
      id: 'reg-7', title: '7 — Emergency Action Plan', icon: 'AlertTriangle', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>7.1</strong> Every year, each Franchise is required to complete an EAP for their home arena(s). Must be submitted to Division Commissioner and RMLL Executive Director by April 20.' },
        { type: 'paragraph', text: '<strong>7.2</strong> The Division Commissioner will send each Franchise the EAPs for all Franchises in their Division by April 30.' },
      ],
    },
    {
      id: 'reg-8', title: '8 — Division Play', icon: 'Calendar', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: '<strong>8.1</strong> Regular Season play will commence no earlier than the last weekend of April and no later than the middle of the second week in May and be finished no later than the last week in July.' },
        { type: 'paragraph', text: '<strong>8.2</strong> Division Game Days:' },
        { type: 'table', headers: ['Division', 'Game Days'], rows: [
          ['Senior B', 'Mon, Wed, Fri, Sat, Sun'],
          ['Senior C', 'Mon, Thu, Fri, Sat, Sun'],
          ['Junior A', 'Wed, Fri, Sat, Sun'],
          ['Tier I', 'Tue, Thu, Fri, Sat, Sun'],
          ['Tier II', 'Mon, Wed, Fri, Sat, Sun'],
          ['Senior Major Female', 'Mon, Tue, Fri, Sat, Sun'],
          ['Junior Major Female', 'Mon, Wed, Fri, Sat, Sun'],
        ]},
        { type: 'paragraph', text: '<strong>8.3</strong> Junior A and Junior B Tier I Pre-Season Practice Days — Junior A will not schedule floor times on Tuesday and Thursday and Junior B Tier I will not schedule floor times on Monday and Wednesday for January through April.' },
        { type: 'paragraph', text: '<strong>8.4</strong> Division Playoffs will commence no earlier than five (5) days following the completion of Regular Season play.' },
        { type: 'paragraph', text: '<strong>8.5</strong> ALA Provincials or RMLL Championships will be finished no later than seven (7) days before a scheduled National Championship.' },
      ],
    },
    {
      id: 'reg-9-17', title: '9–17 — Schedules, Postponements, Defaults, Uniforms, Rules of Play, Game Operations, Officials', icon: 'FileText', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '9 — Season Schedules' },
        { type: 'paragraph', text: '<strong>9.1</strong> Off Season/Pre-Season: Each Franchise must complete a Team Event entry in the RMLL Team Management System for all Franchise lacrosse activities held in Alberta during the off season/pre-season.' },
        { type: 'paragraph', text: '<strong>9.2</strong> Regular Season: Each Division must determine scheduling constraints at annual Division Planning Meeting. "In Progress" schedule completed by March 1. Schedules moved to "final" by March 15.' },
        { type: 'paragraph', text: '<strong>9.3</strong> Division Playoffs, RMLL Championships and ALA Provincials: Provincial format confirmed by August 15. Facilities confirmed 5 days prior to start of each round.' },
        { type: 'paragraph', text: '<strong>9.4–9.5</strong> All games are to be played as scheduled unless determined otherwise by the Division Commissioner. If the start of the game is delayed more than thirty (30) minutes, the Officials may determine if the game will or will not be played.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '10 — Postponements' },
        { type: 'paragraph', text: '<strong>10.1</strong> No game may be postponed without the approval of the Division Commissioner, otherwise such games will be considered as defaults.' },
        { type: 'paragraph', text: '<strong>10.2–10.3</strong> In the event of severe weather, the home Franchise shall immediately call the Division Commissioner to report conditions and request postponement. If the Visiting Franchise has left for the game, the Home Franchise must pay the Officials both the game rate and mileage/per diem rate.' },
        { type: 'paragraph', text: '<strong>10.4</strong> If rain or other condition makes the playing area unfit after the game has started, the Official may stop the game; if forty minutes have been played, it will constitute a Regular Season game.' },
        { type: 'paragraph', text: '<strong>10.4.1</strong> For Playoff/Provincial games: less than 40 min = rescheduled; more than 40 min with 6+ goal spread = constitutes a game; more than 40 min with less than 6 goal spread = rescheduled with restrictions.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '11 — Defaults' },
        { type: 'paragraph', text: '<strong>11.1.1</strong> A defaulting Franchise shall pay all legitimate expenses. The non-defaulting Franchise shall be awarded two (2) points in standings.' },
        { type: 'paragraph', text: '<strong>11.1.2</strong> A Franchise which defaults a game in a Provincial, RMLL Championship or Playoff series shall be suspended immediately.' },
        { type: 'paragraph', text: '<strong>11.2.1</strong> In the event a Franchise folds after their Division Schedule has been created, in addition to a RMLL fine, the Franchise will be responsible for all costs incurred for creating a revised Division Schedule.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '12 — Uniforms' },
        { type: 'paragraph', text: '<strong>12.1</strong> As per LC Rules. <strong>12.2</strong> All RMLL Franchises must have home and away uniforms. Home is the dark colour and away is the light colour. <strong>12.3</strong> Any Franchise showing up to a game without their proper colour jerseys will be subject to a fine.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '13 — Rules of Play' },
        { type: 'paragraph', text: '<strong>13.1</strong> Rules of play in RMLL shall be those of the LC Rule Book, in RMLL Regulations (including Schedule 11), and in the ALA Regulations for the current season.' },
        { type: 'paragraph', text: '<strong>13.2</strong> Overtime — Regular Season: 2-minute rest then 5-minute sudden victory overtime. If still tied, game declared a tie (1 point each). Playoff/Provincial: Continue after 2-minute rest for full 10-minute stop time. If still tied, 10-minute rest then 20-minute periods until sudden victory goal.' },
        { type: 'paragraph', text: '<strong>13.3–13.6</strong> Official Report required for straight time or shortened intermissions. Officials must record bench count. Home Franchise gets delay of game penalty if Off Floor Officials not in place. Water breaks may be allowed on goalie request.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '14 — Maintenance of Order' },
        { type: 'paragraph', text: '<strong>14.1</strong> Home Franchise must supply all Off-Floor Officials (18+ years old, trained, unbiased). ALRA assigns shot clock Official for Playoff/Championship/Provincial games.' },
        { type: 'paragraph', text: '<strong>14.2–14.6</strong> Off-Floor Officials are under supervision of On-Floor Officials and must remain neutral. Timekeepers in place 15 min prior. Two copies of game sheet to scorekeeper 15 min before. Home Franchise responsible for cleaning blood, water and sweat from playing surface. Any person under 18 going on the floor during game periods must wear a helmet and facemask.' },
        { type: 'paragraph', text: '<strong>14.7–14.12</strong> Home Franchise responsible for police protection if deemed necessary. Home Franchise provides 20 warm-up balls to the visiting Franchise. Music allowed only during dead ball stoppages. Arena horns only when a goal is scored. Noncompliance results in warning for first offence and $1,000 fine for each additional offence.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '15 — ALRA Official Assignment' },
        { type: 'paragraph', text: '<strong>15.1–15.5</strong> The Official Assignor will assign Officials with appropriate qualifications and minimize the number of times the same Official officiates the same Franchise. In Playoffs/Championships/Provincials, the best Officials available will be assigned. Shot clock Official must have qualifications to officiate. Officials will not officiate games where a relative is playing or coaching.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '16 — Official Game Fee Payment' },
        { type: 'paragraph', text: '<strong>16.1–16.3</strong> All Officials to be paid prior to the start of each game by the Home Franchise. Each Official paid by cheque or cash (exact amount).' },
        { type: 'paragraph', text: '<strong>Official Game Fees (per Official):</strong> Junior A and Senior B — $85.00 | Senior C and Junior B Tier I — $79.00 | Junior B Tier II, Tier III, Sr. & Jr. Major Female — $73.00' },
        { type: 'paragraph', text: '<strong>16.5–16.7</strong> NSF cheque fine: $50.00. If Officials not paid before game start, Officials will not proceed and game will be declared a default. Official "No Show" procedures apply.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '17 — ALRA Official Reimbursement' },
        { type: 'paragraph', text: '<strong>17.1</strong> Official Driver Mileage — $0.53/km round-trip, first 50 km not paid until round-trip exceeds 50 km.' },
        { type: 'paragraph', text: '<strong>17.2</strong> Official Passenger Mileage — $0.15/km round-trip, first 50 km not paid until round-trip exceeds 50 km.' },
        { type: 'paragraph', text: '<strong>17.3</strong> Official Per Diem — $30.00 when round-trip exceeds 200 km (no overnight). For overnight trips, $70.00/day.' },
        { type: 'paragraph', text: '<strong>17.4–17.5</strong> Hotel Accommodation booked by ALRA VP; RMLL invoices split between Franchises. Officials assigned to inter-provincial games submit expense claims for parking, flights, hotel, mileage and per diem.' },
      ],
    },
    {
      id: 'reg-18-20', title: '18–20 — Game Sheets, Referee Evaluation, Statistics', icon: 'FileText', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '18 — Game Sheets' },
        { type: 'paragraph', text: '<strong>18.1–18.2</strong> Each Franchise receives game sheets at the annual RMLL Planning Meeting and AGM. Manager responsible for completion. Players listed, including call-ups, cannot exceed 18 runners and 2 goalies.' },
        { type: 'paragraph', text: '<strong>18.3</strong> Call-ups identified with "AP", in-home with "IH", captain with "C", assistant captains with "AC".' },
        { type: 'paragraph', text: '<strong>18.4</strong> All game sheets scanned and e-mailed by noon the day after the game to the RMLL Statistician, Division Commissioner and RMLL Executive Director. Submitting is the home Franchise\'s responsibility.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '19 — RMLL Post-Game Referee Evaluation Form' },
        { type: 'paragraph', text: '<strong>19.1–19.3</strong> Form located on RMLL website. Head Coach from both Franchises must complete after game. Forms submitted with game sheet.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '20 — Statistics' },
        { type: 'paragraph', text: '<strong>20.1</strong> Each Home Franchise must enter stats from game sheet for Division home games. Stats not entered for Exhibition Games.' },
        { type: 'paragraph', text: '<strong>20.2–20.4</strong> Franchises not using app must enter box score first. Person entering stats must be set up with "game sheet entry" role. All stats verified by RMLL Statistician.' },
        { type: 'paragraph', text: '<strong>20.5</strong> Game sheet information cannot be changed unless: wrong player credited, additional game misconduct not recorded, too many game misconducts recorded, or penalty recorded doesn\'t exist.' },
      ],
    },
    {
      id: 'reg-21-33', title: '21–33 — Personnel, Players, Rosters, Trades', icon: 'Users', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '21 — Bench Personnel and Managers' },
        { type: 'paragraph', text: '<strong>21.1–21.2</strong> Each Franchise must designate one person as Head Coach. Each Junior and Senior Major Female Franchise must have one female coach registered as Bench Personnel.' },
        { type: 'paragraph', text: '<strong>21.3–21.5</strong> All coaches and trainers must comply with LC minimum standard certification requirements. All Alberta Franchise Bench Personnel and managers must be registered in the RMLL RAMP Intent-to-Play Staff Registration. Opens December 1, closes July 15 – 11:59 PM. Late registration subject to $50.00 ALA fee.' },
        { type: 'paragraph', text: '<strong>21.7–21.10</strong> Only roster coaches/trainers allowed on bench during games. Player Coaches only allowed in Senior C and Senior Major Female. In Senior B, an individual can be both player and coach but not both on the same game sheet. For Playoff/Championship/Provincial play, only coaches with LC minimum standards allowed on bench.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '22 — Rostering of a Minor Lacrosse Aged Player' },
        { type: 'paragraph', text: '<strong>22.1</strong> No player required to register with a Minor Association shall register with a RMLL Franchise unless there is not a U17 team available (may apply for underage exemption for Junior B Tier II).' },
        { type: 'paragraph', text: '<strong>22.2</strong> Any Minor aged player registered to a RMLL Franchise without approved underage exemption shall result in suspension of the player and the coach.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '23 — Rostered Players' },
        { type: 'paragraph', text: '<strong>23.1</strong> The RMLL shall have jurisdiction over all amateur Box players who are a minimum of 17 years of age as of December 31 in the year they wish to compete.' },
        { type: 'paragraph', text: '<strong>23.2</strong> Senior Divisions open to players 22+ years of age. No player under 22 on December 31 shall be on a Senior Franchise roster. Active professional players not eligible to play Senior C.' },
        { type: 'paragraph', text: '<strong>23.3–23.8</strong> Senior B Franchise holds playing rights per 50/40 Player Protected List. Senior C and Senior Major Female hold rights per previous season final roster until released, traded or not on roster as of May 1.' },
        { type: 'paragraph', text: '<strong>23.9–23.11</strong> Junior Divisions open to players under 22 and minimum 17 years of age on December 31. A Junior or Senior player who last played outside Alberta or never played in Alberta is a Free Agent unless on a Protected List.' },
        { type: 'paragraph', text: '<strong>23.12–23.21</strong> Each year the ALA provides lists of Female and Male Graduating U17 players. Junior A — 60/50 Player Protected List. Junior B Tier I — 45/35 Player Protected List. Tier II has detailed boundary rules. Junior Major Female has 40/35 Player Protected List for Calgary area.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '24 — Player Eligibility' },
        { type: 'paragraph', text: '<strong>24.1</strong> All Alberta RMLL players must complete an Intent-to-Play. Opens December 1, closes July 15 11:59 PM. Late registrations not allowed. Link: rmll.rampregistrations.com' },
        { type: 'paragraph', text: '<strong>24.2–24.3</strong> To be eligible, a player must be listed on the Franchise roster in the RMLL Franchise Management System. A player who last played in a LC Jurisdiction outside Alberta must have a completed LC Transfer on file with the ALA.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '25 — Franchise Responsibility - Player Eligibility Violations' },
        { type: 'paragraph', text: '<strong>25.1–25.3</strong> Any Franchise playing an ineligible player shall default all games won during which said player was a participant. Non-defaulting team awarded two (2) points. A Franchise that willfully conceals knowledge of ineligible players shall be considered equally guilty.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '26 — Player Movement' },
        { type: 'paragraph', text: '<strong>26.1–26.4</strong> The RMLL Executive reserves discretionary powers to disallow any proposed player movement not in the best interests of lacrosse. A player on a roster shall not play for another Franchise without first being properly released. Release by Primary or Secondary Contact sending e-mail to Division Commissioner and Executive Director. Once released, a player becomes a Free Agent and property of the RMLL.' },
        { type: 'paragraph', text: '<strong>26.5–26.11</strong> Any rostered player who plays more than ten (10) games and is then released cannot register with a lower Division in that year. A player refused a release may appeal to Division Commissioner. If a Franchise ceases to operate, the Division will decide whether to hold a dispersal draft or allow players to become free agents.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '27 — Trades' },
        { type: 'paragraph', text: '<strong>27.1–27.7</strong> Both Franchises send written acknowledgement to Division Commissioner for approval. Draft picks cannot be traded to a Franchise not in the same draft boundary. A traded player cannot end up back on the original Franchise in the same Season. "Future Consideration" trades should be avoided. Upon approval, Commissioner forwards trade to Executive Director for posting.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '28 — Player Lists' },
        { type: 'paragraph', text: '<strong>28.1</strong> Entry Draft Lists — Draft process documented in separate schedules. Senior Entry Drafts for aged-out Juniors. Junior Entry Drafts for U17 Graduating players.' },
        { type: 'paragraph', text: '<strong>28.2</strong> LC Negotiation List — Senior B, Junior A, and Junior B Tier I must submit maximum 25 players prior to February 23.' },
        { type: 'paragraph', text: '<strong>28.3–28.5</strong> Division Team XX Player Protected Lists managed in Schedules 7-10. Franchise Roster entered in RMLL Franchise Management System. Maximum players: Jr. A & Tier I = 25; Sr. B & Jr. Major Female = 30; Sr. C & Sr. Major Female = 40; Jr. B Tier II = 25 + 5 Tier III.' },
        { type: 'paragraph', text: '<strong>28.5.4</strong> Must be entered by April 27 (or 4 days before first game if season starts before May 1).' },
        { type: 'paragraph', text: '<strong>28.8–28.9</strong> After May 1, a higher-level Franchise may not approach a player from a lower Franchise if it would leave the lower Franchise below 18 players and one goalie. A player becomes a Free Agent at 12:00 am on May 1 if not listed on any Division Protected List.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '29 — Tampering' },
        { type: 'paragraph', text: '<strong>29.1–29.2</strong> No Franchise may contact, influence, practice or play in exhibition games, players who do not come under their jurisdiction. Complaints submitted in writing to Division Commissioner.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '30 — Rosters' },
        { type: 'paragraph', text: '<strong>30.1</strong> Maximum roster sizes: Jr. A & Tier I = 25; Sr. B & Jr. Major Female = 30; Jr. B Tier II = 25 + 5 Tier III; Sr. C & Sr. Major Female = 40.' },
        { type: 'paragraph', text: '<strong>30.4</strong> Player Signing Dates: Start = February 1 (or when Protected List unfreezes). New Player End = July 1, 11:59 pm. Release Date = July 1, 11:59 pm. Released Player Signing End = July 15, 11:59 pm. Trade Dates = February 1 through July 1, 11:59 pm.' },
        { type: 'paragraph', text: '<strong>30.5–30.6</strong> Each Franchise must dress a minimum of eleven (11) players. Playoff/Provincial Play: Player must participate in 4 Regular Season games to qualify (medical exemptions available).' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '31 — Inter-Division Use of Players (Call-ups)' },
        { type: 'paragraph', text: '<strong>31.1–31.4</strong> No player rostered in higher Division may be a call-up in a lower Division. Maximum of four (4) call-ups per game in Regular Season (except Junior A: unlimited for 2025 Season). All call-ups must be properly sanctioned.' },
        { type: 'paragraph', text: '<strong>31.6–31.9</strong> A Senior B Franchise may not scratch a healthy player in place of a call-up. U17 call-ups may play for Tier I, Tier II, Junior Major Female and Senior Major Female (not Junior A, except goalies). Requires parent approval.' },
        { type: 'paragraph', text: '<strong>31.10</strong> Playoff/Provincial Play: Maximum 4 call-ups per game. Player list cannot exceed 25 (or 26 with third goalie) for Junior/Tier divisions, 30 for Senior. Call-up must have played 4 Regular Season games.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '32 — Division, Franchise and Player Affiliations' },
        { type: 'table', title: 'Allowed Division Affiliations', headers: ['Upper Division', 'Call-up From'], rows: [
          ['Senior B', 'Senior C, Jr. A, Jr. B Tier I, Jr. B Tier II'],
          ['Junior A', 'Jr. B Tier I (Protected List), U17 Goalie (emergency)'],
          ['Junior B Tier I', 'Jr. B Tier II, U17'],
          ['Junior B Tier II', 'U17, Jr. Major Female'],
          ['Senior Major Female', 'Jr. Major Female, Female U17'],
          ['Junior Major Female', 'Female U17, Female Tier I & Tier II'],
        ]},
        { type: 'paragraph', text: '<strong>32.2–32.3</strong> Currently the RMLL does not have team affiliations. Player affiliations exist only in Divisions with a XX Player Protected List.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '33 — Roster Exception for Junior B Tier II Teams' },
        { type: 'paragraph', text: '<strong>33.1–33.7</strong> The Tier II Division utilizes a Tier III playing card to allow Tier II Franchises to call-up Tier III players when short. Tier III player eligible for Playoffs if they have played 4 Regular Season Tier II games. Can play for more than one team in Playoffs but cannot play against a team they played for in a previous round.' },
      ],
    },
    {
      id: 'reg-34-36', title: '34–36 — Travel Permits, Exhibition Games, Tournaments', icon: 'FileText', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '34 — Travel Permits' },
        { type: 'paragraph', text: '<strong>34.1–34.3</strong> All Franchises participating in games outside Alberta must obtain approval from their Division Commissioner. Must complete ALA Travel Permit and Roster forms. Request filed 15 days prior to departure. Travel Permit not required for RMLL away games with out-of-province RMLL Members.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '35 — Exhibition Games' },
        { type: 'paragraph', text: '<strong>35.1</strong> An Exhibition Game is any game/scrimmage between players from two different Franchises.' },
        { type: 'paragraph', text: '<strong>35.4–35.7</strong> Permission required from Division Commissioner. Six (6) day minimum notice. Both Franchises enter game details in RMLL System. RMLL Executive Director forwards notification to OIC at least 4 days prior.' },
        { type: 'paragraph', text: '<strong>Exhibition Game Fee Rates (per Official):</strong> Games &gt; 45 min: Jr. B Tier II & Jr/Sr Female = $73; Jr. B Tier I & Sr. C = $79; Jr. A & Sr. B = $85. Games &lt; 46 min: All = $65. Scheduling fee: $6.' },
        { type: 'paragraph', text: '<strong>35.9–35.14</strong> Franchise initiating the Exhibition Game pays game fees. Players must have completed Intent-to-Play. No suspended player may participate. Suspensions in Exhibition Games must be served in RMLL League games. Rosters: max 22 runners and 3 goalies.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '36 — Tournaments' },
        { type: 'paragraph', text: '<strong>36.1–36.4</strong> As per ALA Regulation 6. Discipline Chair is the Division Commissioner. ALA Regulation 6 does not apply to RMLL Playoff/Championship/Provincial Tournament Formats.' },
      ],
    },
    {
      id: 'reg-37-40', title: '37–40 — Standings, Playoffs, Trophies, Nationals', icon: 'Trophy', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '37 — Division Standings' },
        { type: 'paragraph', text: '<strong>37.1–37.2</strong> A win = 2 points. A tie = 1 point each.' },
        { type: 'paragraph', text: '<strong>Balanced Schedule Tiebreakers:</strong> 1. Head-to-head record. 2. Goal Average Formula: GF / (GF + GA) — using only games between tied teams. 3. Goals Against Formula using all games. 4. Lowest penalty minutes.' },
        { type: 'paragraph', text: '<strong>Unbalanced Schedule Tiebreakers:</strong> 1. If played equally: head-to-head, then Goal Average between tied teams. 2. If not played equally: Goal Average using all games. 3. For 3+ teams: same structure, then Goals Against all games, then lowest PIM.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '38 — Playoff, RMLL Championship and Provincial Play' },
        { type: 'paragraph', text: '<strong>38.1</strong> All qualifying Franchises must participate. Failure to participate will result in immediate suspensions and fines.' },
        { type: 'paragraph', text: '<strong>38.2</strong> Overtime rules: 2-minute rest, 10-minute stop time; if still tied, 10-minute rest then 20-minute periods until sudden victory.' },
        { type: 'paragraph', text: '<strong>38.3–38.7</strong> Each Division decides playoff format at annual Planning Meeting. Provincial format confirmed by August 15. The Senior B and Alberta Junior B Tier I Champions represent the ALA at Presidents\' Cup and Founders\' Cup respectively.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '39 — Trophies' },
        { type: 'paragraph', text: '<strong>39.1</strong> Franchises responsible for care and safekeeping. Trophies returned to Executive Director at November Planning Meeting and AGM. <strong>39.1.2</strong> Failure to return may result in a fine of $100 plus $25/month up to twice the replacement cost.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '40 — National Competitions' },
        { type: 'paragraph', text: '<strong>40.1–40.3</strong> Hosting bids due to Commissioner and Executive Director by December 1, two years prior. RMLL selects bid and forwards to ALA by January 15 of year prior.' },
        { type: 'paragraph', text: '<strong>40.4</strong> Franchise attending National Championship may add players from same Division after that player\'s Franchise is eliminated. In Senior B, the lending Franchise\'s consent is required (not unreasonably withheld).' },
        { type: 'paragraph', text: '<strong>40.5</strong> LC Anti-Doping: All athletes and personnel must complete CCES True Sport Clean 101 online education course.' },
      ],
    },
    {
      id: 'reg-41-50', title: '41–50 — Discipline, Protests, Appeals, Social Media, Privacy, Voting', icon: 'AlertTriangle', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '41 — Suspensions and Fines' },
        { type: 'paragraph', text: '<strong>41.1</strong> Official Game Reports: Exhibition/Regular Season = 24 hours; Playoff = 6 hours; Tournament Provincial = 30 minutes.' },
        { type: 'paragraph', text: '<strong>41.2–41.3</strong> Division Commissioner can decrease or increase suspension (max 5 games) and/or fine (max $500). No appeal from suggested suspensions/fines in Regulations 42 and 43.' },
        { type: 'paragraph', text: '<strong>41.7</strong> Immediate suspension for physical contact with an Official. Must appear before Discipline and Appeal Commissioner.' },
        { type: 'paragraph', text: '<strong>41.10–41.15</strong> Match penalty/gross misconduct = suspended until dealt with by Commissioner. Only league games count against suspension. No discipline unless infraction recorded on game sheet by referee. Video evidence may be accepted on case-by-case basis. Control and discipline of spectators and family members is the Franchise\'s responsibility.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '42 — Player Suspensions and Fines' },
        { type: 'paragraph', text: 'Detailed suspension matrices apply for fighting, misconduct, game misconduct, match penalties, gross misconduct, stick infractions, and other penalties. Refer to the full Regulations document for the complete suspension/fine schedule.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '43 — Franchise Suspensions and Fines' },
        { type: 'paragraph', text: 'Detailed fine schedules apply for administrative violations, game operations failures, roster violations, and other infractions. Refer to the full Regulations document for the complete fine schedule.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '44 — Game Protest' },
        { type: 'paragraph', text: 'Written protest must be submitted within 24 hours of game completion. $250.00 protest fee required (refundable if protest upheld). Commissioner reviews and rules within 3 business days.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '45 — Discipline Hearing Process' },
        { type: 'paragraph', text: 'Formal hearing procedures apply. Accused entitled to written notice, right to be heard, and right to present evidence. Committee of 3 members appointed. Decisions by majority vote.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '46 — Appeal Process' },
        { type: 'paragraph', text: 'Appeals must be filed within 7 days. $500 appeal fee required (refundable if appeal upheld). Appeals Committee of 3 members, none of whom served on original Discipline panel.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '47 — Expenses' },
        { type: 'paragraph', text: 'RMLL Executive expense claims submitted monthly. Mileage rate: $0.53/km. Per Diem: $30.00 for day trips over 200 km, $70.00 for overnight.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '48 — Social Media' },
        { type: 'paragraph', text: 'All Members, Members of Members, and Officials are expected to use social media responsibly. Defamatory, threatening, or harassing posts about the RMLL, Officials, or other Members may result in disciplinary action.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '49 — Privacy of Personal Information' },
        { type: 'paragraph', text: 'All personal information collected by the RMLL is subject to the RMLL Privacy Policy. Information shall only be used for RMLL administrative purposes.' },
        { type: 'divider' },
        { type: 'heading', level: 3, text: '50 — Electronic Voting' },
        { type: 'paragraph', text: 'The RMLL Executive may conduct votes electronically between meetings. Electronic votes shall follow the same procedures as in-meeting votes as outlined in the Bylaws.' },
      ],
    },
    {
      id: 'reg-schedules', title: 'Schedules S1–S11', icon: 'Folder', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: 'Schedule 1: LC, ALA, RMLL Calendar - Due Dates' },
        { type: 'paragraph', text: 'Annual calendar of key deadlines for Franchise Certificates, registration, rosters, schedules, fees, and reporting.' },
        { type: 'heading', level: 3, text: 'Schedule 2: New Franchise Certificate Request' },
        { type: 'paragraph', text: 'Application form for new Franchise Certificates including requirements for body corporate registration, board of directors information, and financial guarantees.' },
        { type: 'heading', level: 3, text: 'Schedule 3: Division Tier Change Request' },
        { type: 'paragraph', text: 'Form for requesting a change in playing Division. Must be submitted by November 1.' },
        { type: 'heading', level: 3, text: 'Schedule 4: Franchise Transfer Request' },
        { type: 'paragraph', text: 'Application for transfer of a Franchise from one entity to another, requiring approval of the Division and RMLL Executive.' },
        { type: 'heading', level: 3, text: 'Schedule 5: Franchise Certificate' },
        { type: 'paragraph', text: 'The Franchise Certificate is a certified declaration by a duly elected Officer of the Franchise Holder confirming: authority to execute, review of the Certificate, completeness and accuracy, financial liability, and payment authorization.' },
        { type: 'heading', level: 3, text: 'Schedule 6: Home Facility Specifications' },
        { type: 'paragraph', text: 'Specification form covers: Facility name, availability, playing surface dimensions, ceiling height (minimum 17 feet), surface material, non-slip application, LC lacrosse lines, lighting, air conditioning, players\' box dimensions, timekeeper box, spectator seating, concession, sound system, internet access, admission gate, LC approved nets with black mesh, shot clocks, score clock with penalty minutes, dressing rooms, referee dressing rooms with shower, AED defibrillator.' },
        { type: 'heading', level: 3, text: 'Schedule 7: Senior B Drafts and Protected Lists' },
        { type: 'paragraph', text: '<strong>Senior B Graduating Junior Draft:</strong> Players north of Leduc southern boundary: Beaumont Outlaws, Fort Saskatchewan Rebels, Edmonton Miners. Players south of Didsbury northern boundary: Rockyview Knights, Calgary Senior Mountaineers. Players between: Central Alberta (if established). Once drafted, a player is property of that team until released or traded. If a player goes to a higher league (WLA, MSL), rights remain with drafting team.' },
        { type: 'paragraph', text: '<strong>Senior B 40 Player Protected List:</strong> 50 players allowed Feb 1 – Apr 15; 40 players from Apr 16 – Feb 1 of following year. No Hold-out or Injured Reserve Lists. Frozen from July 1 to February 1. Published on RMLL website.' },
        { type: 'heading', level: 3, text: 'Schedule 8: Junior A Drafts and Protected Lists' },
        { type: 'paragraph', text: '<strong>Junior A Graduating U17 Draft:</strong> 10-round open draft. Draft order based on previous season standings. North draft (Edmonton), South draft (Calgary), Saskatchewan draft. Players north of Lacombe = Edmonton; south of/including Red Deer = Calgary; Saskatchewan = Saskatchewan team.' },
        { type: 'paragraph', text: '<strong>Junior A 50 Player Protected List:</strong> 50-Player Protected List (not a 50-man roster; roster max 25). No hold-out or injury list. Playing rights for full 5 years of junior eligibility. Frozen from July 1 to draft date. Expanded to 60 from draft date until second Sunday in April.' },
        { type: 'heading', level: 3, text: 'Schedule 9: Junior B Tier I Drafts and Protected List' },
        { type: 'paragraph', text: '<strong>Alberta Tier I Drafts (4 separate drafts):</strong> Draft 1 — North: Fort Saskatchewan Rebels, Crude Lacrosse Club, Edmonton Warriors, Beaumont Outlaws (20 rounds, GELC area). Draft 2 — Central: Red Deer Rampage, Mountain View Mavericks (20 rounds, CALL area). Draft 3 — South: Calgary Chill, Calgary Shamrocks, Calgary Mountaineers, Rockyview Silvertips, Okotoks Marauders (20 rounds, CDLA area). Draft 4 — Southern Alberta: Southern Alberta Rockies (20 rounds, southern area clubs).' },
        { type: 'paragraph', text: '<strong>35 Player Protected List:</strong> 35 players (not a roster; roster max 25). Players remain until released, traded, or not on final roster for 2 consecutive seasons. Expanded to 45 from draft date to April 10. Frozen from July 16 to next draft date. Out-of-Province: same structure, frozen July 16 to February 1.' },
        { type: 'heading', level: 3, text: 'Schedule 10: Junior Major Female Draft and Protected Lists' },
        { type: 'paragraph', text: '<strong>Junior Major Female Graduating U17 Draft — Calgary and Surrounding Area:</strong> Draft held prior to February 12 each year. Host alternates among Rockyview Silvertips, Calgary Cardinals, and Okotoks Raiders. Three teams draft from ALA Graduating U17 Female List. Rounds continue until all eligible players drafted or each Franchise reaches 40-player limit.' },
        { type: 'paragraph', text: '<strong>35 Player Protected List — Calgary Area:</strong> 35 players (roster max 30). Players remain until released, traded, or not on final roster for 2 consecutive seasons. Expanded to 40 from draft date to April 5. Frozen from July 1 to next draft date.' },
        { type: 'heading', level: 3, text: 'Schedule 11: RMLL Modified Rules of Play (2024)' },
        { type: 'paragraph', text: '<em>Modified rules of play implemented in 2024. Refer to the full Regulations document for specific rule modifications.</em>' },
      ],
    },
  ],
};
