import type { PageContentSchema } from '../page-content-types';

export const rulesOfPlayDefaults: PageContentSchema = {
  pageId: 'rules-of-play',
  title: 'Rules of Play',
  sections: [
    {
      id: 'header', title: 'Rules of Play', blocks: [
        { type: 'hero', icon: 'BookOpen', title: '2024 RMLL Rules & Procedure Package', subtitle: 'This document serves as a shared resource for all RMLL stakeholders (commissioners, players, coaches, managers, officials, and fans) to be informed by and referenced throughout the season. This has been sourced from previous years OJLL, BCLA and RMLL rule packages/clarifications. 2024 also saw the launch of the <strong>RMLL Casebook</strong>, which provides more information for rules and procedures not necessarily related to the 2024 Playing Rules Updates.<br/><em>Revised April 2, 2024</em>' },
      ],
    },
    {
      id: 'intro', title: 'Introduction', icon: 'BookOpen', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: 'This package outlines the key playing rules and procedures for all RMLL divisions. The rules are based on the LC Rule Book with modifications as outlined in the RMLL Regulations (including Schedule 11) and in the ALA Regulations for the current season.' },
        { type: 'paragraph', text: 'Where a conflict arises between these rules and the Bylaws, Regulations, and Policies of the ALA or LC, the ALA or LC rules will govern.' },
      ],
    },
    {
      id: 'special-note', title: 'Special Note — Crease Dives', icon: 'AlertTriangle', collapsible: true, defaultOpen: false, blocks: [
        { type: 'info-box', variant: 'warning', title: 'Crease Dives', content: 'Any player who dives into the crease (i.e. leaves their feet in an attempt to score by entering the crease) shall be assessed a <strong>2-minute minor penalty for Crease Violation</strong>. The goal, if scored, shall be disallowed.<br/><br/>This rule is designed to protect goaltenders from injury caused by offensive players diving or launching themselves into the crease area. The onus is on the shooter to maintain control.' },
      ],
    },
    {
      id: 'rule-mods', title: '2024 Rule Modifications', icon: 'Wrench', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: '4-Second Count' },
        { type: 'paragraph', text: 'When the horn sounds at the end of a 4-second count violation, it is a "dead ball" and a change of possession will occur. The ball is awarded to the team that was not in possession at the spot of the ball at the time of the horn unless the ball was in the crease area, in which case the faceoff takes place at the nearest faceoff dot.' },
        { type: 'heading', level: 3, text: '8-Second Count' },
        { type: 'paragraph', text: 'When the horn sounds at the end of an 8-second count violation, it is a "dead ball" and a change of possession will occur. The ball is awarded to the opposing team at the center faceoff dot.' },
        { type: 'heading', level: 3, text: 'Face-offs & Restraining Lines' },
        { type: 'paragraph', text: 'On a face-off, all players other than the two facing off must remain behind the applicable restraining lines until possession is gained or the ball crosses a restraining line. Violation of the restraining line prior to possession results in a re-face or, if persistent, a delay of game penalty.' },
        { type: 'heading', level: 3, text: 'Face-off Mechanic' },
        { type: 'paragraph', text: 'Both players must have their stick parallel to the center line, with their right hand on top and their left hand at the bottom of the shaft. The Official will set the ball and step back. On the whistle, both players attempt to gain possession.' },
        { type: 'heading', level: 3, text: 'Delayed Penalty Mechanic' },
        { type: 'paragraph', text: 'When a penalty is to be assessed against a team that does not have possession of the ball, play continues until the offending team gains possession or a stoppage occurs. The non-offending team cannot score an own-goal during this time. An additional player may be placed on the floor by the non-offending team during a delayed penalty (power play advantage).' },
        { type: 'heading', level: 3, text: 'Coincidental Penalties' },
        { type: 'paragraph', text: 'When equal minor penalties are assessed to one player from each team at the same stoppage, the penalties are coincidental. Both players serve their time, but the teams play at full strength (substitutes allowed). Players are released at the first stoppage after their time expires.' },
        { type: 'heading', level: 3, text: '4-on-4 after Coincidental Penalties' },
        { type: 'paragraph', text: 'If coincidental minors are assessed (one to each team) at a stoppage with no other penalties, the result is 4-on-4 play with the minor on the clock as a time-served penalty. Players are released upon expiration of penalty time. This is consistent with current LC rules.' },
        { type: 'heading', level: 3, text: 'Multiple Penalties' },
        { type: 'paragraph', text: 'When multiple penalties are assessed at the same stoppage, the Official must determine coincidental pairs first, then assess remaining penalties in order of least time. The floor cannot go below 3-on-5 — if a third penalty would reduce below this, a penalty shot is awarded instead.' },
        { type: 'heading', level: 3, text: 'Over and Back / Back Over' },
        { type: 'paragraph', text: 'On a face-off, a team may go into their defensive half with the ball off a face-off provided they have not begun traveling towards the opposition\'s goal while in possession or are forced into their defensive half by a defender. This includes carrying, passing or batting a loose ball into their defensive half during the first possession following a face-off.' },
        { type: 'heading', level: 3, text: 'Illegal Substitution' },
        { type: 'paragraph', text: 'A team that has too many men on the floor will be assessed a bench minor penalty. The penalty is assessed against the team, not an individual player, and is served by a player designated by the coach.' },
        { type: 'heading', level: 3, text: 'Fast Restarts' },
        { type: 'paragraph', text: 'After a goal, the ball is placed at the center dot and play may resume immediately. The scoring team must be in their defensive half and the non-scoring team must be in their offensive half before the ball is put in play.' },
        { type: 'heading', level: 3, text: 'In-Homes' },
        { type: 'paragraph', text: 'Each team must designate an In-Home player. The In-Home is used to serve penalties for: goalies, bench minors, and players who are ejected. The In-Home does not serve the penalty personally — they sit in the penalty box to maintain floor strength.' },
        { type: 'heading', level: 3, text: 'Penalty Administration' },
        { type: 'paragraph', text: 'All penalties are administered by the penalty timekeeper. Minor penalties expire either on a goal by the non-offending team or at the end of the penalty time. Major penalties are served in entirety regardless of goals. Misconduct penalties do not affect floor strength.' },
      ],
    },
    {
      id: 'additional-rules', title: 'Additional Rules & Clarifications', icon: 'Info', collapsible: true, defaultOpen: false, blocks: [
        { type: 'heading', level: 3, text: 'Crease-Play' },
        { type: 'paragraph', text: 'No offensive player may enter the crease area at any time. If a player is in the crease when a goal is scored, the goal is disallowed. Defensive players may enter the crease but must not interfere with the goaltender. The crease is defined by the painted lines and extends vertically to the ceiling.' },
        { type: 'heading', level: 3, text: 'Position of Nets' },
        { type: 'paragraph', text: 'Nets must be anchored securely to the floor. If a net is dislodged during play, the Official will stop play and replace the net. A deliberate dislodging of the net by a defensive player results in a penalty shot.' },
        { type: 'heading', level: 3, text: 'Jewelry' },
        { type: 'paragraph', text: 'No player, coach, or official may wear jewelry during a game. This includes rings, necklaces, bracelets, earrings, and piercings. Medical alert bracelets must be taped down or worn under equipment.' },
        { type: 'heading', level: 3, text: 'Illegal Equipment' },
        { type: 'paragraph', text: 'All equipment must conform to LC standards. Sticks are subject to measurement at any time during a game. If a stick is found to be illegal, the player is assessed a minor penalty. Equipment checks may be requested by either team\'s coach.' },
        { type: 'heading', level: 3, text: 'Delay of Game' },
        { type: 'paragraph', text: 'Any action by a player or team that delays the progress of the game may result in a delay of game penalty. This includes: failing to maintain proper bench count, failing to proceed to the face-off area promptly, deliberately shooting the ball out of play, and deliberately freezing the ball against the boards.' },
        { type: 'heading', level: 3, text: 'NLL Possession Rules' },
        { type: 'paragraph', text: 'NLL possession rules are adopted <strong>(with exception of penalties after goals — this will result in possession)</strong>.' },
        { type: 'paragraph', text: '<strong>Who Gets Possession? (CLA Framework):</strong>' },
        { type: 'paragraph', text: '<strong>Before the Whistle:</strong> Non-offending team gets possession. On coincidental penalties, face-off at nearest dot. On a goal, face-off at center.' },
        { type: 'paragraph', text: '<strong>After the Whistle:</strong> Team last in possession retains possession (unless penalty changes it). On out-of-bounds, non-offending team gets possession at nearest restraining line point.' },
        { type: 'heading', level: 3, text: 'Signals' },
        { type: 'paragraph', text: 'Officials use standardized hand and arm signals to communicate penalties, goals, and other game situations. All RMLL officials must be familiar with and consistently use these signals.' },
      ],
    },
    {
      id: 'appendix-a', title: 'Appendix A — Penalty Situations', icon: 'ClipboardList', collapsible: true, defaultOpen: false, blocks: [
        { type: 'paragraph', text: 'The following penalty situation tables are intended to be a reference for commissioners, officials, coaches, players, and managers. They outline common penalty combinations and the resulting floor strength and resolution procedures.' },
        { type: 'info-box', variant: 'info', title: 'RMLL Updates', content: '<strong>Key RMLL-Specific Rules:</strong><br/>• Match penalties in LC play end after 2 goals scored against the penalized team<br/>• Rule 37.2 — "Roll the Box" applies when goals are scored during delayed penalties with penalties already being served<br/>• Floor cannot go below 3-on-5; additional penalties result in penalty shots<br/>• Coincidental minors at same stoppage with no other penalties result in 4-on-4 play' },
        { type: 'heading', level: 3, text: 'Situations 1–3, 15b — Basic Penalties' },
        { type: 'table', headers: ['#', 'Team A', 'Team B', 'Floor', 'Resolution'], rows: [
          ['1', '2 min minor (Player #1)', '—', '5-on-4', 'Team A short-handed. If Team B scores, Player #1 is released.'],
          ['2', '2 min minor (#1) + 2 min minor (#2)', '—', '5-on-3', 'Player #1 serves first. If Team B scores, Player #1 released. If second goal, Player #2 released.'],
          ['3', '2 min minor (#1)', '2 min minor (#3)', '4-on-4', 'Coincidental minors cancel. Both serve penalty time, teams play full strength with substitutes.'],
          ['15b', '2 min minor (#1)', '2 min minor (#3)', '4-on-4', 'Single minor to each team at same stoppage — 4-on-4 with minor on clock as time-served penalty.'],
        ]},
        { type: 'heading', level: 3, text: 'Situations 5–12 — Majors, Stacked Penalties' },
        { type: 'table', headers: ['#', 'Team A', 'Team B', 'Floor', 'Resolution'], rows: [
          ['5', '5 min major (#1)', '—', '5-on-4', 'Major served in entirety. Goals do NOT release Player #1.'],
          ['6', '2 min minor (#1) + 5 min major (#2)', '—', '5-on-3', 'Minor served first. Goal releases minor player. Major continues full 5 min.'],
          ['7', '2 min minor (#1)', '—', '5-on-4', 'Goal scored during delayed penalty on Team B. "Roll the box." Minor still on clock.'],
          ['9', '2+5 min (#1)', '—', '5-on-4', 'Minor served first. Goal cancels minor, major starts.'],
          ['10', '5 min major (#1)', '5 min major (#3)', '4-on-4', 'Coincidental majors. Both serve full 5 min. Full strength with substitutes.'],
          ['12', '2 min minor (#1) + 2 min minor (#2)', '2 min minor (#3)', '5-on-4', 'One coincidental pair cancels. Remaining minor = 5-on-4.'],
        ]},
        { type: 'heading', level: 3, text: 'Situations 13–23 — Misconducts, Goalies, Delayed Penalties' },
        { type: 'table', headers: ['#', 'Team A', 'Team B', 'Floor', 'Resolution'], rows: [
          ['13', '10 min misconduct (#1)', '—', '5-on-5', 'Misconduct does not affect floor strength. Player sits 10 min, substitute allowed.'],
          ['15', '2 min minor + 10 min misconduct (#1)', '—', '5-on-4', 'Minor affects floor strength. Minor served first, then misconduct begins.'],
          ['17', '—', '2 min minor (Goalie)', '5-on-4', 'In-Home or designated player serves the goalie penalty. Goalie stays in net.'],
          ['19', '2 min minor (#1, delayed)', '—', '5-on-4', 'Delayed penalty. Play continues until Team A gains possession or stoppage.'],
          ['22', '2 min minor (#1) + 5 min major+GM (#2)', '—', '5-on-3', 'Player #2 ejected. Major served by In-Home. Team A short 2 players.'],
          ['23', '5 min match penalty (#1)', '—', '5-on-4', 'Match = ejection + review. In RMLL LC play, ends after 2 goals. Served by In-Home.'],
        ]},
        { type: 'heading', level: 3, text: 'Situations 24–43 — Complex Combinations' },
        { type: 'paragraph', text: 'These situations cover complex penalty combinations including stacked penalties with delayed calls, multiple coincidental pairs, penalty shots when floor cannot go below 3, goalie penalties, and In-Home service rules. Key principles:' },
        { type: 'list', items: [
          'Rule 37.2 — Cancel as many coincidental pairs as possible to keep the least players short',
          'Floor cannot go below 3-on-5; additional penalties trigger penalty shots',
          'Majors are served in entirety regardless of goals',
          'Misconduct penalties never affect floor strength',
          'Match penalties in LC play end after 2 goals scored against',
          'Shorthanded goals do NOT release penalty players',
          'Double minors: goal during first half cancels first minor; goal during second half releases player',
        ]},
        { type: 'heading', level: 3, text: 'Situations 44–64 — Advanced Scenarios' },
        { type: 'paragraph', text: 'Advanced penalty situations cover: penalty shots when already 5-on-3, goals scored during delayed penalties with active power plays ("roll the box"), penalty shots that do not cancel serving penalties, end-of-period penalty carryover, coincidental match penalties, and multiple layers of penalties at the same stoppage.' },
        { type: 'info-box', variant: 'info', title: 'Reference', content: 'For the complete penalty situation tables with all 64 scenarios, refer to the full RMLL Rules & Procedure Package document available in the <strong>Documents Library</strong>.' },
      ],
    },
    {
      id: 'footer', title: 'Document Information', blocks: [
        { type: 'paragraph', text: '<em>2024 RMLL Rules & Procedure Package — Revised April 2, 2024</em>' },
        { type: 'paragraph', text: '<em>Original Documents: OLA Jr A/Sr A Document | NLL Casebook | BCLA Document | NLL Rules</em>' },
      ],
    },
  ],
};
